# Generated by Django 6.0.7 on 2026-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['id']},
        ),
    ]
