# Generated by Django 6.0.7 on 2026-08-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the useful report configuration/content snapshot (rows, filters, generated_at) that makes a saved report re-viewable later.'),
        ),
    ]
