# Generated by Django 6.0.7 on 2026-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('SYSTEM', 'System'), ('AI', 'AI Recommendation')], default='SYSTEM', max_length=20),
        ),
    ]
