from rest_framework import serializers
from rest_framework.exceptions import AuthenticationFailed

from rest_framework_simplejwt.tokens import RefreshToken

from core.models import Organization
from .models import User


class RegisterSerializer(serializers.ModelSerializer):
    """
    Register a new Organization and its first Business Admin.

    The Business Code is always generated by the server (never accepted
    from the client) via ``Organization.save`` and is returned read-only
    so the registering admin can save it for future logins.
    """

    organization_name = serializers.CharField(
        max_length=255,
        write_only=True
    )

    organization_email = serializers.EmailField(
        write_only=True
    )

    organization_phone = serializers.CharField(
        max_length=20,
        write_only=True
    )

    organization_address = serializers.CharField(
        required=False,
        write_only=True
    )

    password = serializers.CharField(
        write_only=True
    )

    business_code = serializers.CharField(
        source="organization.code",
        read_only=True,
    )

    organization_code = serializers.CharField(
        source="organization.code",
        read_only=True,
    )

    class Meta:
        model = User

        fields = [
            "username",
            "email",
            "password",
            "phone",
            "organization_name",
            "organization_email",
            "organization_phone",
            "organization_address",
            "business_code",
            "organization_code",
        ]

    def validate_organization_email(self, value):
        if Organization.objects.filter(email=value).exists():
            raise serializers.ValidationError(
                "An organization with this email already exists."
            )
        return value

    def create(self, validated_data):

        organization_kwargs = dict(
            name=validated_data.pop(
                "organization_name"
            ),
            email=validated_data.pop(
                "organization_email"
            ),
            phone=validated_data.pop(
                "organization_phone"
            ),
            address=validated_data.pop(
                "organization_address",
                ""
            ),
        )

        organization = Organization.objects.create(
            **organization_kwargs
        )

        user = User.objects.create_user(
            username=validated_data["username"],
            email=validated_data["email"],
            password=validated_data["password"],
            phone=validated_data.get(
                "phone",
                ""
            ),
            organization=organization,
            role="ADMIN",
            is_verified=True,
        )

        return user


class BusinessTokenObtainSerializer(serializers.Serializer):
    """
    Business Code + Username + Password authentication.

    The flow is:

    1. Resolve the ``business_code`` to an active ``Organization``.
    2. Look the ``username`` up *within that organization* only (the same
       username may exist in different business tenants and remains
       separate).
    3. Verify the password for that exact user.

    A business code is required for every login — there is no organization-less
    (super admin) login path. The authenticated user's ``organization`` then
    stays the authoritative tenant identity for every subsequent request;
    client-supplied tenant identifiers are never accepted after login.
    """

    business_code = serializers.CharField(
        required=False,
        allow_blank=True,
        trim_whitespace=True,
    )

    username = serializers.CharField()

    password = serializers.CharField(
        trim_whitespace=False,
    )

    def _fail(self):
        # Keep the failure reason ambiguous (no user/business enumeration).
        raise AuthenticationFailed(
            "Invalid business code, username or password."
        )

    def validate(self, attrs):
        business_code = (
            attrs.get("business_code") or ""
        ).strip().upper() or None

        username = attrs.get("username")
        password = attrs.get("password")

        if not business_code:
            self._fail()

        organization = Organization.objects.filter(
            code__iexact=business_code,
            is_active=True,
        ).first()

        if organization is None:
            self._fail()

        user = User.objects.filter(
            username=username,
            organization=organization,
            is_active=True,
        ).first()

        if user is None or not user.check_password(password):
            self._fail()

        refresh = RefreshToken.for_user(user)
        refresh["username"] = user.username
        refresh["role"] = user.role
        refresh["organization_id"] = str(user.organization_id or "")
        refresh["organization_code"] = organization.code
        refresh["business_code"] = organization.code

        return {
            "access": str(refresh.access_token),
            "refresh": str(refresh),
            "user": {
                "id": user.id,
                "username": user.username,
                "email": user.email,
                "role": user.role,
                "organization": user.organization.name,
                "organization_id": str(user.organization_id),
                "business_code": organization.code,
            },
        }



class UserSerializer(serializers.ModelSerializer):
    """
    Serializer for the logged-in user.
    """

    organization = serializers.StringRelatedField()

    organization_code = serializers.CharField(
        source="organization.code",
        read_only=True,
    )

    business_code = serializers.CharField(
        source="organization.code",
        read_only=True,
    )

    class Meta:
        model = User

        fields = [
            "id",
            "username",
            "email",
            "phone",
            "role",
            "organization",
            "organization_id",
            "organization_code",
            "business_code",
            "is_verified",
            "created_at",
        ]

        read_only_fields = fields



class StaffSerializer(serializers.ModelSerializer):
    """
    Serializer for creating and managing staff users.
    """

    password = serializers.CharField(
        write_only=True,
        required=False
    )

    class Meta:
        model = User

        fields = [
            "id",
            "username",
            "email",
            "password",
            "phone",
            "is_active",
        ]

        read_only_fields = [
            "id",
        ]


    def create(self, validated_data):
        """
        Create staff user under the logged-in
        Business Admin organization.
        """

        request = self.context["request"]

        user = User.objects.create_user(
            username=validated_data["username"],
            email=validated_data.get(
                "email",
                ""
            ),
            password=validated_data["password"],
            phone=validated_data.get(
                "phone",
                ""
            ),
            organization=request.user.organization,
            role="STAFF",
            is_verified=True,
        )

        return user

    def update(self, instance, validated_data):
        password = validated_data.pop("password", None)

        for attr, value in validated_data.items():
            setattr(instance, attr, value)

        if password:
            instance.set_password(password)

        instance.save()
        return instance