# Generated by Django 6.0.7 on 2026-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sync_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id']},
        ),
    ]
