# Generated by Django 6.0.7 on 2026-08-12 05:19
from decimal import Decimal

from django.db import migrations
from django.db.models import F


def _computed_status(amount_paid, total_amount):
    """Authoritative Phase 18 payment status rules (single source of truth)."""
    paid = amount_paid if amount_paid is not None else Decimal("0.00")
    total = total_amount if total_amount is not None else Decimal("0.00")

    if paid <= Decimal("0.00"):
        return "UNPAID"

    if paid < total:
        return "PARTIAL"

    return "PAID"


def normalize_paid_sales(apps, schema_editor):
    """
    Normalize legacy sales created before the simplified workflow.

    The simplified workflow records a sale as a completed transaction:
    amount_paid = total_amount and payment_status = "PAID". Legacy rows
    were created with amount_paid = 0.00 / "UNPAID" even though they were
    completed sales. The stored amount_paid is set to the sale total so
    the stored payment_status agrees with the computed status.

    Only sales with a non-zero total are touched. Zero-total invoices
    (no line items) keep their recorded UNPAID state, which already
    agrees with the computed status (paid <= 0 => UNPAID). No rows are
    deleted, no financial values other than amount_paid change, and no
    related models (items, inventory, reports) are modified. query.update()
    is used instead of model.save() so no model-level logic or signals run.
    """
    Sale = apps.get_model("sales", "Sale")

    rows = list(
        Sale.objects.filter(total_amount__gt=0)
        .values("pk", "amount_paid", "total_amount")
    )

    for row in rows:
        if row["amount_paid"] == row["total_amount"]:
            continue
        Sale.objects.filter(pk=row["pk"]).update(
            amount_paid=F("total_amount"),
            payment_status="PAID",
        )

    print(
        "\nSales payment-state normalization: "
        f"{len(rows)} rows considered | "
        f"{sum(1 for r in rows if r['amount_paid'] == r['total_amount'])} already consistent"
    )


def reverse_normalize(apps, schema_editor):
    """
    Best-effort reverse: recompute stored payment_status from amounts.

    The original amount_paid values (all 0.00 for the affected legacy
    rows) are the bug this migration fixes and are intentionally not
    restored. Recomputing the stored status from current amounts keeps
    stored and computed statuses consistent after a rollback.
    """
    Sale = apps.get_model("sales", "Sale")

    rows = list(Sale.objects.all().values("pk", "amount_paid", "total_amount"))

    for row in rows:
        status = _computed_status(row["amount_paid"], row["total_amount"])
        Sale.objects.filter(pk=row["pk"]).update(payment_status=status)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleitem_options'),
    ]

    operations = [
        migrations.RunPython(normalize_paid_sales, reverse_normalize),
    ]
