# Generated by Django 6.0.7 on 2026-07-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('FORECAST', 'Demand Forecast'), ('LOW_STOCK', 'Low Stock Prediction'), ('RECOMMENDATION', 'Inventory Recommendation'), ('ANALYSIS', 'Business Analysis')], max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_by', models.CharField(default='AI', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
