# Generated by Django 6.0.7 on 2026-07-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_remove_sale_customer_remove_purchase_organization_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service')], default='RETAIL', max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
